app/transactions/models.py
import datetime
from sqlalchemy.orm import relationship
from app import db


class Transactions(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    transaction_type_id = db.Column(db.Integer, db.ForeignKey('transaction_types.id'), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'), nullable=True)
    amount = db.Column(db.Numeric, nullable=False)
    date = db.Column(db.Date, nullable=False)

    transaction_type = relationship('TransactionTypes', backref='transaction_types')
    category = relationship('Categories', backref='categories')

    def __init__(self, transaction_type, name, amount, date, category=None):
        self.transaction_type = transaction_type
        self.name = name
        if category is not None:
            self.category = category
        self.amount = amount
        self.date = self.str_to_datetime(date)

    @staticmethod
    def str_to_datetime(date: str) -> datetime.date:
        return datetime.datetime.strptime(date, "%m/%d/%Y").date()

    def set_date(self, date: str):
        self.date = self.str_to_datetime(date)

    def get_date(self) -> str:
        return self.date.strftime("%m/%d/%Y")

    def to_json(self) -> dict:
        return {
            'id': self.id,
            'name': self.name,
            'transaction_type': self.transaction_type.id,
            'category': self.category.id,
            'amount': self.amount,
            'date': self.get_date(),
        }


class TransactionTypes(db.Model):
    __tablename__ = 'transaction_types'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)

    def __init__(self, name):
        self.name = name

app/transactions/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash, jsonify
from app.transactions.models import Transactions, TransactionTypes
from app.categories.models import Categories
from app import db


transactions_bp = Blueprint(
    'transactions',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/transactions/static',
)


@transactions_bp.route('/transactions', methods=['GET'])
def transactions():
    ts = Transactions.query.order_by(Transactions.date.desc()).all()
    by_date = {}
    for t in ts:
        try:
            by_date[t.get_date()].append(t)
        except KeyError:
            by_date[t.get_date()] = [t]
    return render_template(
        'transactions.html',
        transactions_by_date=by_date,
        categories=Categories.query.order_by(Categories.name.asc()),
        transaction_types=TransactionTypes.query.order_by(TransactionTypes.name.asc()),
        transactions=Transactions.query.order_by(Transactions.date.desc()).limit(10),
    )


@transactions_bp.route('/transactions/<int:transaction_id>', methods=['GET'])
def get_transaction(transaction_id):
    transaction = Transactions.query.filter_by(id=transaction_id).first()
    return jsonify(transaction.to_json())


@transactions_bp.route('/transactions/new', methods=['POST'])
def new_transaction():
    transaction_type = TransactionTypes.query.filter_by(id=int(request.form['typeSelectorName'])).first()
    if transaction_type.name == 'Expense':
        category = Categories.query.filter_by(id=int(request.form['categorySelectorName'])).first()
    else:
        category = None
    transaction = Transactions(
        transaction_type=transaction_type,
        name=request.form['transactionName'],
        category=category,
        amount=round(float(request.form['amountSelectorName']), 2),
        date=request.form['dateSelectorName'],
    )
    db.session.add(transaction)
    db.session.commit()
    return redirect(url_for('dashboard.dashboard'))


@transactions_bp.route('/transactions/<int:transaction_id>/update', methods=['POST'])
def update_category(transaction_id):
    transaction = Transactions.query.filter_by(id=transaction_id).first()
    #   Date
    transaction.set_date(date=request.form['date'])
    #   Transaction Type
    transaction.transaction_type = TransactionTypes.query.filter_by(id=int(request.form['transactionTypeName'])).first()
    #   Category
    if transaction.transaction_type.name == 'Expense':
        transaction.category = Categories.query.filter_by(id=int(request.form['categoryName'])).first()
    else:
        transaction.category = None
    #   Name
    transaction.name = request.form['transactionName']
    #   Amount
    transaction.amount = round(float(request.form['amount']), 2)
    db.session.commit()
    return redirect(url_for('transactions.transactions'))

app/transactions/templates/transactions.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<link rel="stylesheet" href="{{ url_for('transactions.static', filename='transactions.css')|autoversion }}">
{% endblock %}

{% block main %}

<div class="d-flex align-items-center p-3 my-3 text-white-50 bg-lightblue rounded box-shadow">
    <img class="mr-3" src="{{ url_for('static', filename='budget-v2.svg')|autoversion }}" alt="" width="48" height="48">
    <div class="lh-100">
      <h6 class="mb-0 text-white lh-100">Transactions</h6>
      <small>Since 2021</small>
    </div>
</div>
{% for date, transactions in transactions_by_date.items()%}
<div class="my-3 p-3 bg-white rounded box-shadow">
    <h6 class="border-bottom border-gray pb-2 mb-0">{{date}}</h6>
    {% for transaction in transactions%}
    <div class="media text-muted pt-3 border-bottom border-gray">
        <p class="media-body pb-3 mb-0 small lh-125 update-modal-opener" data-id="{{transaction.id}}" data-toggle="modal">
            <strong class="d-block text-gray-dark">{{transaction.name}}</strong>
            {{transaction.category.name}}
            <p class="mr-2"></p>
            {{"${:,.2f}".format(transaction.amount)}}
        </p>
    </div>
    {% endfor %}
</div>
{% endfor %}

<!--            -->
<!-- MODAL      -->
<!-- for update -->
<!--            -->

<div class="modal fade" id="updateTransactionsModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <!--        -->
            <!-- Header  -->
            <!--        -->
            <div class="modal-header">
                <h5 class="modal-title">Update Transaction</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"> &times;</span>
                </button>
            </div>
            <!--        -->
            <!-- Body  -->
            <!--        -->
            <div class="modal-body">
                <form action="{{ url_for('transactions.transactions') }}" method="get">
                    <!--    Date    -->
                    <div class="input-group date mb-3" data-provide="datepicker">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Date</span>
                        </div>
                        <input id="date" name="date" type="text" class="form-control">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                    <!--    Type    -->
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <label class="input-group-text" for="transactionTypeName">Type</label>
                      </div>
                      <select name="transactionTypeName" class="custom-select" id="transactionTypeName">
                          {% for transaction_type in transaction_types %}
                           <option value="{{transaction_type.id}}">{{transaction_type.name}}</option>
                          {% endfor %}
                      </select>
                    </div>
                    <!--    Category    -->
                    <div class="input-group mb-3" id="categoryNameSelector">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Category</span>
                      </div>
                      <select id="categoryName" name="categoryName" class="form-control">
                          {% for category in categories %}
                           <option value="{{category.id}}">{{category.name}}</option>
                          {% endfor %}
                      </select>
                    </div>
                    <!--    Name    -->
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Name</span>
                        </div>
                        <input id="transactionName" name="transactionName" type="text" class="form-control" aria-label="Category Name" required="1">
                        <div class="input-group-append"></div>
                    </div>
                    <!--    Amount    -->
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">$</span>
                        </div>
                        <input id="amount" name="amount" type="number" step="0.01" class="form-control" aria-label="Amount (to the nearest dollar)" required="1">
                        <div class="input-group-append"></div>
                    </div>
                    <!--    SUBMIT    -->
                    <button type="submit" class="btn btn-secondary" onclick="UpdateTransaction()">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!--            -->
<!-- MODAL      -->
<!-- for new    -->
<!--            -->

<button class="material-icons floating-button-add-entry" id="addEntryBtn"> add </button>

<div class="modal fade" id="addEntryModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <!--        -->
            <!-- Header  -->
            <!--        -->
            <div class="modal-header">
                <h5 class="modal-title">Add Entry</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"> &times;</span>
                </button>
            </div>
            <!--        -->
            <!-- Body  -->
            <!--        -->
            <div class="modal-body">
                <form action="{{ url_for('transactions.new_transaction') }}" method="post">
                    <div class="input-group date mb-3" data-provide="datepicker" id="datepicker">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Date</span>
                        </div>
                        <input name="dateSelectorName" type="text" value ="today();" class="form-control">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <label class="input-group-text" for="typeSelector">Type</label>
                      </div>
                      <select name="typeSelectorName" class="custom-select" id="typeSelector">
                          {% for transaction_type in transaction_types %}
                           <option value="{{transaction_type.id}}">{{transaction_type.name}}</option>
                          {% endfor %}
                      </select>
                    </div>
                    <div class="input-group mb-3" id="categorySelector">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Category</span>
                      </div>
                      <select name="categorySelectorName" class="form-control">
                          {% for category in categories %}
                           <option value="{{category.id}}">{{category.name}}</option>
                          {% endfor %}
                      </select>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Name</span>
                        </div>
                        <input name="transactionName" class="form-control" aria-label="Amount (to the nearest dollar)" required="1">
                        <div class="input-group-append"></div>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">$</span>
                        </div>
                        <input name="amountSelectorName" type="number" step="0.01" class="form-control" aria-label="Amount (to the nearest dollar)" required="1">
                        <div class="input-group-append"></div>
                    </div>
                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"
        integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ=="
        crossorigin="anonymous"></script>
<script src="{{ url_for('transactions.static', filename='transactions.js')|autoversion }}"></script>
{% endblock %}